public  class Opportunity {

    public static void getOpportunity() {
        string name = 'The Australian animated television series Bluey has broadcast 104 episodes since its debut on ABC Kids Deepak on 1 October 2018. The series was created by Joe Brumm with the Queensland production group Ludo Studio.';
   		boolean check = name.contains('Kumar');
        system.debug('check@@'+check);
    }

}